trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals my-windows-agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: wiz@0
  displayName: "Wiz Image Scan"
  inputs:
    command: 'image'
    clientid: $(WIZ_CLIENT_ID)
    secret: $(WIZ_CLIENT_SECRET)
    succeedOnFailures: true
    policyHitsOnly: false
    path: '.'
    image: 'mcr.microsoft.com/windows:ltsc2019'
    name: 'Windows LTSC2019 Image Scan'
    scanSecrets: true
